version: '3.8'
services:
  api:
    build:
      context: ./
      target: dev
    volumes:
      - .:/app
    command: npm run start:dev
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
      DEBUG: nodejs-docker-express:*
  db:
    image: postgres:bullseye
    environment:
      POSTGRES_USER: taxi_brousse
      POSTGRES_PASSWORD: taxi_brousse
      POSTGRES_DB: taxi_brousse
    ports:
      - "5432:5432"